name: 00 - Main CI / CD Pipeline

on:
  workflow_dispatch:
#   push:
#     branches: [ "main" ]
#     paths-ignore:
#       - '**/*.md'
#       - '**/*.txt'
  # pull_request:
  #   branches: [ "main" ]
  # Run weekly at midnight on Sunday MINUTE HOUR DAY_OF_MONTH MONTH DAY_OF_WEEK
  # schedule:
  #   - cron: "0 0 * * 0"  

permissions:
  contents: write
  security-events: write
  actions: read
  checks: write
  packages: write
  issues: write

jobs:
#   sonar-qube:
#     name: Sonar Qube
#     uses: ./.github/workflows/static-code-quality-check.yml

  sca:
    name: SCA
    # needs: [sonar-qube]
    uses: ./.github/workflows/sca.yml
    secrets: inherit

  dast:
    name: DAST
    needs: [sca]
    uses: ./.github/workflows/dast.yml
    secrets: inherit

  license-compliance:
    name: License compliance
    needs: [dast]
    uses: ./.github/workflows/license-compliance.yml
    secrets: inherit
  
#   build-and-push-to-ghcr:
#     name: Build Image And Push
#     needs: [license-compliance]
#     uses: ./.github/workflows/docker-build-push.yml
#     secrets: inherit